
input_select:
  wled_presets:
    options:
      - "[01] Preset 1"
      - "[02] Preset 2"
      - "[03] Preset 3"
      - "[04] Preset 4"
      - "[05] Preset 5"
      - "[06] Preset 6"
      - "[07] Preset 7"
      - "[08] Preset 8"
      - "[09] Preset 9"
      - "[10] Preset 10"
      - "[11] Preset 11"
      - "[12] Preset 12"
      - "[13] Preset 13"
      - "[14] Preset 14"
      - "[15] Preset 15"
      - "[16] Preset 16"

  wled_palette_list:
    options:
      - "[00] Default"
      - "[01] Random Cycle"
      - "[02] Primary color"
      - "[03] Based on primary"
      - "[04] Set colors"
      - "[05] Based on set"
      - "[06] Party"
      - "[07] Cloud"
      - "[08] Lava"
      - "[09] Ocean"
      - "[10] Forest"
      - "[11] Rainbow"
      - "[12] Rainbow bands"
      - "[13] Sunset"
      - "[14] Rivendell"
      - "[15] Breeze"
      - "[16] Red & Blue"
      - "[17] Yellowout"
      - "[18] Analoguous"
      - "[19] Splash"
      - "[20] Pastel"
      - "[21] Sunset 2"
      - "[22] Beech"
      - "[23] Vintage"
      - "[24] Departure"
      - "[25] Landscape"
      - "[26] Beach"
      - "[27] Sherbet"
      - "[28] Hult"
      - "[29] Hult 64"
      - "[30] Drywet"
      - "[31] Jul"
      - "[32] Grintage"
      - "[33] Rewhi"
      - "[34] Tertiary"
      - "[35] Fire"
      - "[36] Icefire"
      - "[37] Cyane"
      - "[38] Light Pink"
      - "[39] Autumn"
      - "[40] Magenta"

input_number:
  ledspeed:
    name: Speed
    initial: 0
    min: 0
    max: 255
    step: 1
  ledintensity:
    name: LED Intensity
    initial: 0
    min: 0
    max: 255
    step: 1
  ledbrightness:
    name: LED Brightness
    initial: 0
    min: 0
    max: 255
    step: 1
